# Generated by Django 4.1.1 on 2022-09-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_rename_group_associationmemeber_member_group_and_more'),
        ('account', '0002_associationpayment_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationMemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='Account balance')),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='association.associationmemeber')),
            ],
            options={
                'verbose_name': 'Association member account',
                'verbose_name_plural': 'Association member accounts',
                'db_table': 'association_member_account_tb',
            },
        ),
        migrations.CreateModel(
            name='AssociationMemberTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='Amount Paid')),
                ('topup', models.BooleanField(default=False)),
                ('date_paid', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='account.associationlevycharge')),
                ('member_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.associationmemberaccount')),
            ],
            options={
                'verbose_name': 'Association transaction',
                'verbose_name_plural': 'Association transactions',
                'db_table': 'association_transactions_tb',
            },
        ),
        migrations.DeleteModel(
            name='AssociationPayment',
        ),
    ]
