# Generated by Django 4.1.1 on 2022-09-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_associationmemberaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationmemberaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000000, verbose_name='Account balance'),
        ),
    ]
