# Generated by Django 4.1.1 on 2022-09-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_rename_group_associationmemeber_member_group_and_more'),
        ('account', '0004_alter_associationmemberaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationmemberaccount',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='association.associationmemeber'),
        ),
    ]
