# Generated by Django 4.1.1 on 2022-09-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_associationmemberaccount_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmembertransaction',
            name='description',
            field=models.CharField(blank=True, default='not specified', max_length=200),
        ),
    ]
