# Generated by Django 4.1.1 on 2022-09-14 22:16

import association.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=association.models.handle_upload_dir, verbose_name='Logo')),
                ('name', models.CharField(max_length=255, verbose_name='Associatin name')),
                ('contacts', models.CharField(max_length=100, verbose_name='Contacts')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('town', models.CharField(max_length=100, verbose_name='Town')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('local_government', models.CharField(max_length=100, verbose_name='Local government')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'db_table': 'associations_tb',
            },
        ),
    ]
