# Generated by Django 4.1.1 on 2022-09-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='contacts',
        ),
        migrations.AddField(
            model_name='association',
            name='contact',
            field=models.CharField(default='+234 8000000000', max_length=100, verbose_name='Contact'),
            preserve_default=False,
        ),
    ]
