# Generated by Django 4.1.1 on 2022-09-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_remove_association_contacts_association_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='group_label',
            field=models.CharField(default='streets', max_length=100, verbose_name='Group Label'),
        ),
        migrations.CreateModel(
            name='AssociationGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Associatin name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='association.association')),
            ],
            options={
                'verbose_name': 'Association group',
                'verbose_name_plural': 'Association groups',
                'db_table': 'association_groups_tb',
            },
        ),
    ]
