# Generated by Django 4.1.1 on 2022-09-19 12:41

import association.models_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0003_association_group_label_associationgroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationgroups',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Association name'),
        ),
        migrations.CreateModel(
            name='AssociationMemeber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(blank=True, null=True, upload_to=association.models_utils.handle_upload_passport, verbose_name='Passport')),
                ('first_name', models.CharField(max_length=255, verbose_name='Member first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Member last name')),
                ('group_no', models.CharField(max_length=100, verbose_name='Member group number')),
                ('contact', models.CharField(max_length=100, verbose_name='Member contact')),
                ('gender', models.CharField(max_length=10, verbose_name='Member gender')),
                ('date_of_birth', models.DateField(verbose_name='Member date of birth')),
                ('religion', models.CharField(max_length=100, verbose_name='Member religion')),
                ('nationality', models.CharField(max_length=100, verbose_name='Member nationality')),
                ('state_of_origin', models.CharField(max_length=100, verbose_name='Member state of origin')),
                ('ethnicity', models.CharField(max_length=100, verbose_name='Member ethnicity')),
                ('local_government_of_origin', models.CharField(max_length=100, verbose_name='Member local government of origin')),
                ('occupation', models.CharField(max_length=100, verbose_name='Member occupation')),
                ('next_of_kin', models.CharField(max_length=100, verbose_name='Member next of kin')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='association.associationgroups')),
            ],
            options={
                'verbose_name': 'Association Member',
                'verbose_name_plural': 'Association Members',
                'db_table': 'association_memeber_tb',
            },
        ),
    ]
