# Generated by Django 4.1.1 on 2022-09-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_alter_associationgroups_name_associationmemeber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associationmemeber',
            old_name='group',
            new_name='member_group',
        ),
        migrations.RemoveField(
            model_name='associationmemeber',
            name='group_no',
        ),
        migrations.AddField(
            model_name='association',
            name='registration_id',
            field=models.CharField(default='CDA/101/XXX', max_length=255, verbose_name='Association registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='associationmemeber',
            name='group_id',
            field=models.CharField(default='not specified', max_length=100, verbose_name='Member group identification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='associationmemeber',
            name='next_of_kin_contact',
            field=models.CharField(default='+234 800000000', max_length=100, verbose_name='Member next of kin contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Association name'),
        ),
    ]
